### ISSUE TITLE
pfx and passphrase

### ISSUE THREAD

**Issue by WorkAlexGahr** [visionmedia/superagent#1222] opened 2017-05-05 15:57 UTC
Hi,

seems i cannot use pfx() and passphrase in an https request allthough it works find in node https.request.
Is there any way i can set the passphrase?

Regards 
Alex

**Comment by pornel** [comment] 2017-05-05 17:04
It should work. I don't know why it doesn't. Duplicate of #1213

**Closed by pornel** 2017-05-05 17:04 UTC
