### ISSUE TITLE
Http post call, sometimes callback is not getting executed.

### ISSUE THREAD

**Issue by RajeshSivanesan** [visionmedia/superagent#984] opened 2016-05-09 15:31 UTC
Http post call, sometimes callback is not getting executed, its getting stuck.

Is there any case, where callback wont get invoked ? Is it enough to listen for end events alone, do i need any special listeners ?

**Comment by pornel** [comment] 2016-05-09 15:40
Usually it should be enough to just wait for the `end` event.

Does it consistently get stuck in some specific situation?

**Comment by RajeshSivanesan** [comment] 2016-05-09 16:31
// state change
 xhr.onreadystatechange = function () {
    if (4 != xhr.readyState) return;

    // In IE9, reads to any property (e.g. status) off of an aborted XHR will
    // result in the error "Could not complete the operation due to error c00c023f"
    var status;
  	try { status = xhr.status; } catch(e) { status = 0; }

    if (0 == status) {
      if (self.timedout) return self.timeoutError();
      if (self.aborted) return;
      return self.crossDomainError();
    }
    self.emit('end');
  };

if(4 != xhr.readyState) return;

if the readyState in any case will not change to 4 ? Status still staying on 3.

I will confirm if Iam able to reproduce this always. I just wanna understand, are there any cases in which this can happen ?

**Comment by pornel** [comment] 2016-05-09 20:20
By the spec it must change to 4 when the connection ends. Does network inspector in devtools show the connection is still running?

**Comment by RajeshSivanesan** [comment] 2016-05-11 10:54
I tried different ways of reproducing this, but always the readyState changes to 4 always. If i find the exact steps to reproduce, will let you know.

**Comment by pornel** [comment] 2016-05-11 11:17
BTW: if you're finding this problem in production, it may be caused by network/browser issues, e.g. I've seen users with data caps on 3G connections have their connections throttled down to 0, so they never finish, but never fail either. Setting something like `.timeout(30000)` on all requests helps.

**Comment by pornel** [comment] 2016-05-29 18:23
I presume it's been fixed in #985

**Closed by pornel** 2016-05-29 18:23 UTC
