### ISSUE TITLE
Something is wrong with redirects

### ISSUE THREAD

**Issue by kof** [visionmedia/superagent#412] opened 2014-07-07 15:23 UTC
I have got this url: http://goldhaber.org/?feed=rss2&cat=23
It responds with 310 and new location header. Superagent sends something on 2. try that causes the server to redirect it to a different url again and again util we reach the limit.

Browser follows it with no issues.

**Comment by defunctzombie** [comment] 2015-02-22 04:08
Closing due to age. If a simple example is provided I can run to reproduce, happy to take a closer look.

**Closed by defunctzombie** 2015-02-22 04:08 UTC
Labels: Bug
