### ISSUE TITLE
Getting error "Origin is not allowed by Access-Control-Allow-Origin" in browser when no internet connection

### ISSUE THREAD

**Issue by scottnonnenberg** [visionmedia/superagent#679] opened 2015-06-18 18:27 UTC
I'm getting a "Origin is not allowed by Access-Control-Allow-Origin" error from superagent in Chrome 43 on OSX when I attempt to hit a service that does not respond, or when the internet connection has been turned off entirely.

Seems that [`Request.prototype.crossDomainError`](https://github.com/visionmedia/superagent/blob/94afa3ae189267a8d352d72b20edb9900148959e/lib/client.js#L847) is called too often? Maybe some more checks should be added in [`Request.prototype.end`](https://github.com/visionmedia/superagent/blob/94afa3ae189267a8d352d72b20edb9900148959e/lib/client.js#L913) before falling through to `crossDomainError()`?

**Comment by xcatliu** [comment] 2015-08-07 09:41
+1

**Comment by nalwayaabhishek** [comment] 2015-09-16 05:48
+1 I am getting the same error when no internet connection

**Comment by scsper** [comment] 2015-09-23 22:08
+1

**Comment by crcn** [comment] 2015-09-23 22:45
+1

**Comment by benjdezi** [comment] 2015-09-23 22:46
+1

**Comment by WenXuanYuan** [comment] 2015-10-29 13:34
The same error occured with me !

**Comment by scsper** [comment] 2015-11-18 23:00
@defunctzombie Any guidance on what to do?  I'm willing to open the pull request, but I'd like some community support before putting in the work.

**Comment by pornel** [comment] 2015-11-30 23:06
Agreed this is a problem. Duplicate of  #484

**Closed by pornel** 2015-11-30 23:06 UTC

**Comment by askucher** [comment] 2018-09-16 02:46
+1
