### ISSUE TITLE
double callback on large post data

### ISSUE THREAD

**Issue by dkimdon** [visionmedia/superagent#351] opened 2014-03-31 21:27 UTC
Hi,
     
     I ran into what I think is this bug and I have created an archive that
     allows it to be reproduced.   I looked at issue #313 and issue #290
     and I don't think I am making the same mistakes that are outlined in
     those issues.  The general thing I am trying to do is to limit the
     size of the post data the server receives, and then have a test that
     shows the size limit is enforced.  The size limit is 128 bytes.  Here
     is the test printing out the double callback warning:
     
     
     $ tar xzf superagent-313.tar.gz 
     $ cd superagent-313
     $ ls
     app.js  Makefile  package.json  test
     $ find .
     .
     ./Makefile
     ./package.json
     ./test
     ./test/working.js
     ./test/buggy.js
     ./app.js
     $ npm install
     supertest@0.9.0 node_modules/supertest
     ├── methods@0.1.0
     └── superagent@0.16.0 (methods@0.0.1, cookiejar@1.3.0, debug@0.7.4, qs@0.6.5, emitter-component@1.0.0, reduce-component@1.0.1, mime@1.2.5, formidable@1.0.14)
     
     mocha@1.17.1 node_modules/mocha
     ├── debug@0.8.0
     ├── diff@1.0.7
     ├── growl@1.7.0
     ├── commander@2.0.0
     ├── mkdirp@0.3.5
     ├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
     └── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
     
     express@3.4.8 node_modules/express
     ├── methods@0.1.0
     ├── merge-descriptors@0.0.1
     ├── debug@0.8.0
     ├── range-parser@0.0.4
     ├── cookie-signature@1.0.1
     ├── fresh@0.2.0
     ├── buffer-crc32@0.2.1
     ├── cookie@0.1.0
     ├── mkdirp@0.3.5
     ├── commander@1.3.2 (keypress@0.1.0)
     ├── send@0.1.4 (mime@1.2.11)
     └── connect@2.12.0 (uid2@0.0.3, pause@0.0.1, qs@0.6.6, bytes@0.2.1, raw-body@1.1.2, batch@0.5.0, negotiator@0.3.0, multiparty@2.2.0)
     $ make test
     ./node_modules/mocha/bin/mocha --reporter list 
     
       ․ data buggy: 259ms
     double callback!
     double callback!
       ․ data working: 38ms
     
       2 passing (364ms)
     
     $ diff -u ./test/working.js test/buggy.js 
     --- ./test/working.js	2014-03-31 21:10:41.000000000 +0000
     +++ test/buggy.js	2014-03-31 21:06:03.000000000 +0000
     @@ -2,9 +2,9 @@
      var request = require('supertest');
      
      describe('data', function() {
     -    it('working', function(done) {
     +    it('buggy', function(done) {
              var data = '';
     -        for (i = 0 ; i < 5000 ; i++) {
     +        for (i = 0 ; i < 50000 ; i++) {
                  s =  Math.random().toString(36).slice(2);
                  data += s;
              }
     $
     
     As you can see in teh diff above, the only difference between the two
     tests is the size of the uploaded data.
     
     If I run the server under node in the normal way all works as
     expected:
     
     $ node app.js 
     server listening on port 8100
     
     . . .
     
     Then I send it some requests, first a small request, won't be
     rejected:
     
     $  curl 'http://l--verbose  -d "small"
     * Hostname was NOT found in DNS cache
     *   Trying 127.0.0.1...
     * Connected to localhost (127.0.0.1) port 8100 (#0)
     > POST /data/whatever HTTP/1.1
     > User-Agent: curl/7.35.0
     > Host: localhost:8100
     > Accept: */*
     > Content-Length: 5
     > Content-Type: application/x-www-form-urlencoded
     > 
     * upload completely sent off: 5 out of 5 bytes
     < HTTP/1.1 200 OK
     < X-Powered-By: Express
     < Date: Mon, 31 Mar 2014 21:20:25 GMT
     < Connection: keep-alive
     < Transfer-Encoding: chunked
     < 
     * Connection #0 to host localhost left intact
     small$ 
     
     Now a large request that will be rejected:
     
     $  curl 'http://localhost:8100/data/whate--verbose  -d
     "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
     * Hostname was NOT found in DNS cache
     *   Trying 127.0.0.1...
     * Connected to localhost (127.0.0.1) port 8100 (#0)
     > POST /data/whatever HTTP/1.1
     > User-Agent: curl/7.35.0
     > Host: localhost:8100
     > Accept: */*
     > Content-Length: 240
     > Content-Type: application/x-www-form-urlencoded
     > 
     * upload completely sent off: 240 out of 240 bytes
     < HTTP/1.1 413 Request Entity Too Large
     < X-Powered-By: Express
     < Date: Mon, 31 Mar 2014 21:21:05 GMT
     < Connection: keep-alive
     < Transfer-Encoding: chunked
     < 
     * Connection #0 to host localhost left intact
     413: Request Entity Too Large$

**Comment by seriousben** [comment] 2015-02-10 16:50
Getting this as well.
```js
t('upload png too large', function(done) {
       appRequest.post('/api/files')
      .attach('file', path.join(__dirname, './fixtures/largeImage.png'))
      .set('Accept', 'application/json')
      .expect(400)
      .send(function(err, res) {
        done();
      });
  });
```

**Comment by defunctzombie** [comment] 2015-07-29 20:37
Closing this due to age and lack of repo to reproduce.

**Closed by defunctzombie** 2015-07-29 20:37 UTC
